name: bicep-ci-cd

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AZURE_RG: rg-bicep-sec-baseline-dev
  DEPLOYMENT_NAME: main
  TEMPLATE_FILE: main.bicep

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Bicep
        run: az bicep install

      - name: Bicep compile (build)
        run: az bicep build --file $TEMPLATE_FILE

      - name: Azure What-If
        run: |
          az deployment group what-if \
            --resource-group $AZURE_RG \
            --name $DEPLOYMENT_NAME \
            --template-file $TEMPLATE_FILE \
            --parameters enableSentinel=true deployAnalyticsRules=true

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy (RG scope)
        run: |
          az deployment group create \
            --resource-group $AZURE_RG \
            --name $DEPLOYMENT_NAME \
            --template-file $TEMPLATE_FILE \
            --parameters enableSentinel=true deployAnalyticsRules=true
